### PR TITLE
Implement running commands via start-process

### LINKED ISSUE #8: Convert all process code to 'start-process'
Right now, `alda-mode` uses `start-process-shell-command` to play alda notes, which is dependent on the shell and operating system that you are using. If we switch this over to a plain `start-process`, this should make `alda-mode` a lot more portable and should cleanly work across every operating system. 

See #7 for more info. 

This probably blocks #6

### PR DESCRIPTION
**Pull request by jgkamat**
Hopefully adds windows and other OS support cleanly

Still using a shell-command to check if the alda server is up though..

Closes #8.

If you have some spare time, please test this out and makes sure this works for you! I'll be testing this on all my machines (currently just linux and windows).

### CODE REVIEW

**Comment by jgkamat** [comment]
@kjmatsuda could you try and test this PR out on your machine (to verify that windows support is working correctly?) I was going to try it myself, but I'm running into https://github.com/alda-lang/alda-core/issues/31, so I can't until that's fixed.

**Comment by kjmatsuda** [comment]
@jgkamat Hi! OK, I will test it and inform you the result in a few days!

**Comment by kjmatsuda** [comment]
I tested your code, and the result is all OK :thumbsup:

OS: Windows 10
Emacs: 25.1
Alda: 1.0.0-rc56

Input text is like this.
> trumpet:  o4 c8 d e f g a b > %last-note c4.~2
> trombone: o3 e8 f g a b > c d e4.~2
> tuba: @last-note o2 c4.~2

Test cases are like this.
1. C-c C-r	alda-play-region
   1) select first line, then trumpet is played. -> OK
   2) select second line, then trombone is played. -> OK
   3) select all lines, then trumpet and trombone and tuba are played. -> OK

2. C-c C-c	alda-play-block
   trumpet and trombone and tuba are played. -> OK

3. C-c C-n	alda-play-line
   1) point at first line, then trumpet is played. -> OK
   2) point at second line, then trombone is played. -> OK
   
4. C-c C-b	alda-play-buffer
   trumpet and trombone and tuba are played. -> OK

If there are other test cases you want me to test, please let me know!

**Comment by jgkamat** [comment]
Thanks for the quick response! That should be enough, since all the commands have the same behavior it should all work.

Thanks again for testing this out! :smile:  :tada:

**Comment by jgkamat** [comment]
Merging now, let me know if anyone sees any issues! :)

**Pull request merged**
